# Generated by Django 4.0.6 on 2022-07-28 11:19

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.CharField(default=api.models.generate_code, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('body', models.CharField(default='', max_length=250)),
                ('creator', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
